<a href="https://colab.research.google.com/github/angelakorm/emotion-recogniton/blob/main/Emotion_Recognition_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries

In [328]:
import numpy as np
import pandas as pd
import tensorflow as tf
import kagglehub
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

## Import dataset

In [329]:
path = kagglehub.dataset_download("rahmasleam/emotions-rml-dataset")
dataset = pd.read_csv(path + '/Emotion_classify_Data.csv')
dataset.head()

Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [330]:
X = dataset.iloc[:, 0].values
print(X)

['i seriously hate one subject to death but now i feel reluctant to drop it'
 'im so full of life i feel appalled'
 'i sit here to write i start to dig out my feelings and i think that i am afraid to accept the possibility that he might not make it'
 ...
 'i were to ever get married i d have everything ready to offer to him because i ve got it together and when i do go out to clubs even the perfect good looking guys feel intimated after talking to me about my clever self'
 'i feel reluctant in applying there because i want to be able to find a company where i know at least one person'
 'i just wanted to apologize to you because i feel like a heartless bitch']


In [331]:
y = dataset.iloc[:, -1].values
print(y)

['fear' 'anger' 'fear' ... 'joy' 'fear' 'anger']


## Label emotions

In [332]:
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 1 ... 2 1 0]


## Convert text to vectors

In [333]:
cv = CountVectorizer()
X = cv.fit_transform(X)
print(X.toarray()[:1, :])

[[0 0 0 ... 0 0 0]]


## Split train and test set

In [334]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature scaling

In [335]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train.toarray())
X_test = sc.transform(X_test.toarray())

# Build model

In [336]:
ann = tf.keras.models.Sequential()
for i in (0,15):
  ann.add(tf.keras.layers.Dense(units=30, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

# Train model

In [337]:
ann.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.4141 - loss: 1.5468
Epoch 2/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.8894 - loss: 0.4326
Epoch 3/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9837 - loss: 0.0880
Epoch 4/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9970 - loss: 0.0269
Epoch 5/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9979 - loss: 0.0160
Epoch 6/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9991 - loss: 0.0107
Epoch 7/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9987 - loss: 0.0117
Epoch 8/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9992 - loss: 0.0065
Epoch 9/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9994 - loss: 0.0047
Epoch 10/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9998 - loss: 0.0030
Epoch 11/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9996 - loss: 0.0033
Epoch 12/100
149/149 ━━━━━━━━━━━━━━━━━━

## Predict

In [338]:
y_pred = ann.predict(X_test)
y_pred_class = np.argmax(y_pred, axis=1)
print(np.concatenate((y_pred_class.reshape(-1,1), y_test.reshape(-1,1)), axis=1))

38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[1 0]
 [1 1]
 [2 2]
 ...
 [1 1]
 [2 2]
 [1 1]]


## Evaluate

In [339]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred_class)
print(cm)
accuracy_score(y_test, y_pred_class)

[[343  40  33]
 [ 53 292  28]
 [ 38  40 321]]


0.8047138047138047