<a href="https://colab.research.google.com/github/angelakorm/emotion-recogniton/blob/main/Emotion_Recognition_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Import libraries

In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf
import kagglehub
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

## Import dataset

In [44]:
path = kagglehub.dataset_download("rahmasleam/emotions-rml-dataset")
dataset = pd.read_csv(path + '/Emotion_classify_Data.csv')
dataset.head()

Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [45]:
X = dataset.iloc[:, 0].values
print(X)

['i seriously hate one subject to death but now i feel reluctant to drop it'
 'im so full of life i feel appalled'
 'i sit here to write i start to dig out my feelings and i think that i am afraid to accept the possibility that he might not make it'
 ...
 'i were to ever get married i d have everything ready to offer to him because i ve got it together and when i do go out to clubs even the perfect good looking guys feel intimated after talking to me about my clever self'
 'i feel reluctant in applying there because i want to be able to find a company where i know at least one person'
 'i just wanted to apologize to you because i feel like a heartless bitch']


In [46]:
y = dataset.iloc[:, -1].values
print(y)

['fear' 'anger' 'fear' ... 'joy' 'fear' 'anger']


## Label encode emotions

In [47]:
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 1 ... 2 1 0]


## Convert text to vectors

In [48]:
cv = CountVectorizer()
X = cv.fit_transform(X)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Split train and test set

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature scaling

In [50]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train.toarray())
X_test = sc.transform(X_test.toarray())